language: python
sudo: required
fast_finish: true
before_install:
  - python --version
# command to install dependencies
  # update docker to edge
#install:
#  - pip3 install -U codecov
script:
  - ./build-docs.sh
  - ls -al
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  local_dir: site
  on:
    branch: master
